### ISSUE TITLE
feature: popover/tip on badge hover

### ISSUE THREAD

**Issue by Daniel-Boll** [basementdevs/twitch-addon-scylladb-rs#12]
![image](https://github.com/user-attachments/assets/4a75b7a0-a27b-4558-8727-bd658515dd09)

The default behavior of twitch badges is to show a popover/tip when hovering over a badge, describing what it means. It seems like it get the info from the `aria` attributes from the image, but for that the button parent may need a event listener, I will investigate it further.

**Comment by DanielHe4rt** [comment]
I guess we should bring this as a prio in the upcoming hotfixes releases. Or maybe create something around it... Still thinking in ideas.
