### ISSUE TITLE
chore: setup lint config

### ISSUE THREAD

**Issue by gvieira18** [basementdevs/twitch-addon-scylladb-rs#15]
Currently the api and extension don't have a **lint** config, so each dev uses their own config from the IDE's. In my opnion this can be complex in the future for reviewing some pull requests.

I know on Javascript we can use/combine some options to lint the code:

- [Eslint](https://eslint.org/)
- [Prettier](https://prettier.io/)
- [Editorconfig](https://editorconfig.org/)
- [Husky](https://typicode.github.io/husky/)
- [lint-staged](https://github.com/lint-staged/lint-staged)
- [biome](https://biomejs.dev/)

Note that the lint config can be annoying when using Plasmo, like the [empty object](https://github.com/basementdevs/twitch-addon-scylladb-rs/blob/4fe924b9a7591b8f8c59699ad0bf732bb5c2aeae/extension/src/content.ts#L5) at the beginning of the file.

For Rust, the [documentation](https://doc.rust-lang.org/book/appendix-04-useful-development-tools.html) mentions using [`rustfmt`](https://github.com/rust-lang/rustfmt) and [`clippy`](https://github.com/rust-lang/rust-clippy), but I don't know if there are any other options.

**Comment by henrique-leme** [comment]
I can work on the lint configuration for the TS side of the project if someone haven't started it yet
