### ISSUE TITLE
feature: update previous chat messages after first load

### ISSUE THREAD

**Issue by DanielHe4rt** [basementdevs/twitch-addon-scylladb-rs#2]
## Issue
Currently, the `content.ts` only listens to the new messages in the chat. However, I would like to load for previous messages as well.

![Chat Loading with messages](https://github.com/user-attachments/assets/1975b740-f09a-444a-b6b2-24e8172ca427)

## Goal

Make the previous messages that got loaded after you join the room get tagged with pronoun and the default icon (which is already attached and it's called mod.png).

**Comment by leandrogrillo** [comment]
@DanielHe4rt Can I try to help? :) 

I don't get how to run it properly. I enabled the dev mod in the browser, but the auth button doesn't work as expected. (or maybe I'm doing something wrong)

**Comment by DanielHe4rt** [comment]
@leandrogrillo I'll spent some minutes enhancing the documentation and I'll get back to you.

**Comment by DanielHe4rt** [comment]
@leandrogrillo Now we have a proper Readme for running the extension. 

The only thing which is a problem is that the `CLIENT_ID` is hardcoded at `background/messages/oauth.ts`. We plan to add environment variables soon as possible but so far you would have to change manually to yours.

**Comment by leandrogrillo** [comment]
@DanielHe4rt Thanks! I'll check it out, and if I find any problems, I'll message you back! :D 

>We plan to add environment variables soon as possible but so far you would have to change manually to yours.
I saw that, and I was about to say it XD but it's all good! 

Thanks again ^^
