### ISSUE TITLE
Twitch Profiler - Button hierarchy suggests that logging out is the most important action on the screen

### ISSUE THREAD

**Issue by Grazinascito** [basementdevs/twitch-addon-scylladb-rs#30]
The logout button at the bottom of the app breaks fundamental UI/UX design principles. It looks like a call-to-action (CTA), implying that logging out is the most important action on the screen, which isn't the case. To align with good design principles, I suggest replacing the button with a smaller logout icon next to the moon icon. This approach follows the consistency law, as most apps have logout buttons that are small and less prominent.

<img width="358" alt="Screenshot 2024-08-07 at 11 46 20" src="https://github.com/user-attachments/assets/8d9424d7-ff84-4055-9df0-0ca8c33acf47">

**Comment by Grazinascito** [comment]
source: https://balsamiq.com/learn/articles/button-design-best-practices/ 
https://app.uxcel.com/courses/ui-components-n-patterns/anatomy-iii-298

**Comment by DanielHe4rt** [comment]
I like the proposal and you can send a Pull Request with a suggestion! I'd love to have a contribution from you <3
