### ISSUE TITLE
ERROR: Failed to resolve './gen-assets/icon16.plasmo.png' during manifest transformation

### ISSUE THREAD

**Issue by M4teusPrado** [basementdevs/twitch-addon-scylladb-rs#42]
I encountered an error while building my Twitch extension using Plasmo. During the manifest transformation step, the build process fails when attempting to resolve several icon files that are supposed to be located in the ./gen-assets/ directory. The error message suggests that files like icon16.plasmo.png, icon32.plasmo.png, among others, cannot be found in the specified directory.

![image](https://github.com/user-attachments/assets/883181ec-acf3-44a0-b67c-2308572aa6d5)

Steps to Reproduce:

- Run the build process using Plasmo with the following command: `npm run build`
- The process starts and attempts to transform the manifest (**firefox-mv2.plasmo.manifest.json**).
- The following error message is displayed: ` ERROR | Failed to resolve './gen-assets/icon16.plasmo.png' in './.plasmo/firefox-mv2.p`

**Comment by voomsuetam** [comment]
I tried to reproduce the error, but everything works fine for me.
Is your `main` branch updated? It looks like PR #38 might have already resolved this issue.

**Comment by M4teusPrado** [comment]
Thank you very much, everyone. The error was exactly as described, and we have resolved the issue
