### ISSUE TITLE
fix: version is not showing in white mode

### ISSUE THREAD

**Issue by voomsuetam** [basementdevs/twitch-addon-scylladb-rs#44]
![Peek 2024-08-09 01-01](https://github.com/user-attachments/assets/54963ee7-af3c-4b69-b61c-8bb55bf9097e)

**Comment by DanielHe4rt** [comment]
Fixed https://github.com/basementdevs/twitch-addon-scylladb-rs/commit/fe7bb6b5459aa1fb628da0c0b60770e7a86ced04.
